sudo: required
services:
  - docker

before_install:
  - docker build -t jdsoftwarestudio/multi-docker-test -f ./client/Dockerfile.dev ./client

script:
  - docker run jdsoftwarestudio/multi-docker-test npm test -- --coverage

after_success:
  - docker build -t jdsoftwarestudio/multi-client ./client
  - docker build -t jdsoftwarestudio/multi-nginx ./nginx
  - docker build -t jdsoftwarestudio/multi-server ./server
  - docker build -t jdsoftwarestudio/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push jdsoftwarestudio/multi-client
  - docker push jdsoftwarestudio/multi-nginx
  - docker push jdsoftwarestudio/multi-server
  - docker push jdsoftwarestudio/multi-worker